"""The reader's own contract, apart from any enclosure that uses it."""

from __future__ import annotations

import string
from pathlib import Path
from typing import Any

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from stompgeom.step import (
    _EPOCH,
    StepLabel,
    bounding_box_mm,
    leaf_labels,
    read_step,
    source_timestamp,
)
from stompmodel.errors import DocumentError

from .xcaf import BODY_SIZE_MM, build_document

#: Printable ASCII with no control character and no backslash, so a
#: generated string can never hit the writer's own STEP special-character
#: encoding (``\N\``, ``\T\``, and a literal backslash's own doubling) or its
#: NUL truncation -- none of that is this reader's concern, which reads only
#: the quote-doubling ``FILE_NAME``'s own field carries (ISO 10303-21 §6).
_PLAUSIBLE_FIELD_TEXT = "".join(
    c for c in string.printable if c not in "\t\n\r\x0b\x0c\\"
)


def test_source_timestamp_reads_a_real_st_developer_header(tmp_path: Path) -> None:
    """A genuine ST-Developer file, annotated with a comment naming each
    field immediately before that field's own value -- the dialect the old
    comment-matching pattern was written for, and the one real committed
    fixture and every cached Hammond model actually use. The value must come
    from ``FILE_NAME``'s own field, not merely from the comment beside it."""
    target = tmp_path / "st-developer.stp"
    target.write_bytes(
        b"ISO-10303-21;\n"
        b"HEADER;\n"
        b"/* Generated by software containing ST-Developer\n"
        b" * from STEP Tools, Inc. (www.steptools.com) \n"
        b" */\n"
        b"\n"
        b"FILE_DESCRIPTION(\n"
        b"/* description */ (''),\n"
        b"/* implementation_level */ '2;1');\n"
        b"\n"
        b"FILE_NAME(\n"
        b"/* name */ \n"
        b"'1590B.iam.stp',\n"
        b"\n"
        b"/* time_stamp */ '2014-07-28T13:46:15-04:00',\n"
        b"/* author */ ('rboehler'),\n"
        b"/* organization */ (''),\n"
        b"/* preprocessor_version */ 'ST-DEVELOPER v15.2',\n"
        b"/* originating_system */ 'Autodesk Inventor 2014',\n"
        b"/* authorisation */ '');\n"
        b"\n"
        b"FILE_SCHEMA (('AUTOMOTIVE_DESIGN { 1 0 10303 214 3 1 1 }'));\n"
        b"ENDSEC;\n"
    )

    assert source_timestamp(target) == "2014-07-28T13:46:15-04:00"


def test_source_timestamp_falls_back_to_the_epoch_with_no_file_name(
    tmp_path: Path,
) -> None:
    """Never a clock reading: determinism does not depend on the file
    carrying a stamp, only on every write copying the same value."""
    target = tmp_path / "bare.stp"
    target.write_bytes(b"ISO-10303-21;\n")

    assert source_timestamp(target) == _EPOCH


def test_source_timestamp_falls_back_to_the_epoch_when_the_field_is_empty(
    tmp_path: Path,
) -> None:
    """A declared but empty ``time_stamp`` field degrades to the sentinel
    rather than putting an empty string into a report."""
    target = tmp_path / "empty-stamp.stp"
    target.write_bytes(b"FILE_NAME('a name','',('author'),('org'),'p','s','');\n")

    assert source_timestamp(target) == _EPOCH


def test_source_timestamp_reads_past_a_doubled_quote_in_the_preceding_field(
    tmp_path: Path,
) -> None:
    """A literal quote in the ``name`` field is written doubled (``''``);
    that must not be mistaken for the field's closing quote, which would
    otherwise hand the timestamp field's own value to the wrong capture."""
    target = tmp_path / "escaped-name.stp"
    target.write_bytes(
        b"FILE_NAME('it''s a name','2014-07-28T13:46:15-04:00',"
        b"('author'),('org'),'p','s','');\n"
    )

    assert source_timestamp(target) == "2014-07-28T13:46:15-04:00"


def test_source_timestamp_unescapes_a_doubled_quote_in_its_own_field(
    tmp_path: Path,
) -> None:
    """The timestamp field itself may carry an escaped quote; the reader
    must return the one real character, not the two-character encoding."""
    target = tmp_path / "escaped-stamp.stp"
    target.write_bytes(
        b"FILE_NAME('name','it''s stamped',('author'),('org'),'p','s','');\n"
    )

    assert source_timestamp(target) == "it's stamped"


def test_source_timestamp_pattern_has_no_catastrophic_backtracking(
    tmp_path: Path,
) -> None:
    """A run of quotes with no closing ``FILE_NAME`` call must not make the
    match pathological: each alternative in the string-literal branch
    consumes a distinct, unambiguous prefix, so this returns in linear time
    rather than hanging the process."""
    target = tmp_path / "pathological.stp"
    target.write_bytes(b"FILE_NAME(" + b"'" * 20000)

    assert source_timestamp(target) == _EPOCH


@settings(deadline=None, max_examples=25)
@given(
    timestamp=st.text(alphabet=_PLAUSIBLE_FIELD_TEXT, min_size=1, max_size=40),
)
def test_render_step_timestamp_survives_its_own_round_trip_for_any_value(
    timestamp: str, tmp_path_factory: pytest.TempPathFactory
) -> None:
    """Criterion 1's class property: no single hard-coded string can satisfy
    this, only a reader that recovers the field the writer actually set --
    whatever value that field held, including one containing the delimiters
    (``,`` ``(`` ``)``) and the quote character the writer itself escapes.

    ``tmp_path_factory``, not ``tmp_path``: a function-scoped fixture is not
    reset between ``@given`` examples, and this needs a fresh file each time.
    """
    from stompgeom.writer import render_step

    payload = render_step(
        build_document(),
        title="a title",
        timestamp=timestamp,
        originating_system="an originating system",
    )
    target = tmp_path_factory.mktemp("round-trip") / "written.stp"
    target.write_bytes(payload)

    assert read_step(target).timestamp == timestamp


def test_reading_a_missing_file_is_a_document_error(tmp_path: Path) -> None:
    """A stompgeom reader cannot raise a stompdrill error; refusing a foreign
    document is a failure any member can have, so the base is shared.

    The message says "model", not "case model": an enclosure is one thing a
    caller might have been reading, and this layer knows about none of them.
    """
    with pytest.raises(DocumentError, match="no model at"):
        read_step(tmp_path / "absent.stp")


def test_reading_a_non_step_file_is_a_document_error(tmp_path: Path) -> None:
    """Not readable is distinct from not present, and both are the file's
    fault rather than the data's."""
    target = tmp_path / "rubbish.stp"
    target.write_bytes(b"this is not a STEP file at all\n")

    with pytest.raises(DocumentError, match="is not a readable STEP file"):
        read_step(target)


# ---------------------------------------------------------------------------
# The reader driven against a file this package wrote, needing no download
# ---------------------------------------------------------------------------


def _written(tmp_path: Path) -> Path:
    """A real STEP assembly, built in memory and written by this package."""
    from stompgeom.writer import render_step

    target = tmp_path / "round-trip.stp"
    payload = render_step(
        build_document(),
        title="a round trip",
        timestamp="2020-01-02T03:04:05",
        originating_system="a supplied originating system 9.9",
    )
    target.write_bytes(payload)
    return target


def test_read_step_returns_every_leaf_solid_and_no_assembly(tmp_path: Path) -> None:
    """``leaf_labels`` recurses past an assembly label rather than recording
    it, so three components come back as three solids under their own names."""
    document = read_step(_written(tmp_path))

    assert len(document.solids) == 3
    assert {"body", "lid"} <= {solid.name for solid in document.solids}


def test_read_step_places_each_solid_in_assembly_coordinates(tmp_path: Path) -> None:
    """``leaf_labels``'s central claim: reading the *component* label applies the
    placement its parent gave it. The lid is modelled at the origin like the
    body and lifted 5 mm by the assembly, so a reader taking the referred
    product label instead would hand it back sitting at zero."""
    document = read_step(_written(tmp_path))
    (body,) = document.named("body")
    (lid,) = document.named("lid")

    assert bounding_box_mm(body.shape)[2] == pytest.approx(0.0, abs=1e-6)
    assert bounding_box_mm(lid.shape)[2] == pytest.approx(5.0, abs=1e-6)


def test_bounding_box_mm_measures_a_solid_in_millimetres(tmp_path: Path) -> None:
    """The extent the document was built with, which is also what proves the
    reader's unit normalisation left a millimetre model alone."""
    (body,) = read_step(_written(tmp_path)).named("body")
    x0, y0, z0, x1, y1, z1 = bounding_box_mm(body.shape)

    assert (x1 - x0, y1 - y0, z1 - z0) == pytest.approx(BODY_SIZE_MM, abs=1e-6)


def test_a_file_this_package_wrote_reads_back_its_own_timestamp(
    tmp_path: Path,
) -> None:
    """The layer closed under its own round trip (ADR-0008): this writer
    emits no ST-Developer ``/* time_stamp */`` comment, but it does set
    ``FILE_NAME``'s own field, and that is the field the reader now reads."""
    target = _written(tmp_path)

    assert b"'2020-01-02T03:04:05'" in target.read_bytes()
    assert read_step(target).timestamp == "2020-01-02T03:04:05"


# ---------------------------------------------------------------------------
# leaf_labels -- the one XCAF leaf descent, published for every caller
# ---------------------------------------------------------------------------


def test_leaf_labels_of_an_empty_document_is_empty() -> None:
    """No free shapes at all is not an error; it is an empty result."""
    document, _shapes = _new_shape_tool()

    assert leaf_labels(document) == ()


def test_leaf_labels_does_not_filter_a_null_shaped_leaf() -> None:
    """What a leaf is *for* is a call-site decision, not this function's:
    a leaf with no shape at all is returned like any other, not skipped."""
    from OCP.TopoDS import TopoDS_Shape

    document, shapes = _new_shape_tool()
    label = shapes.AddShape(_a_box(), False)
    shapes.SetShape(label, TopoDS_Shape())

    (found,) = leaf_labels(document)
    assert found.label.IsEqual(label)
    assert found.document is document


def test_leaf_labels_returns_leaves_not_assemblies() -> None:
    """An assembly's own label never comes back, only its leaf components --
    the distinction ``read_step`` relies on to avoid double-counting a solid."""
    document, component = _named_occurrence_document("body")

    found = leaf_labels(document)

    assert len(found) == 1
    assert found[0].label.IsEqual(component)


# ---------------------------------------------------------------------------
# StepLabel.name -- the one rule for what XCAF recorded as a label's name
# ---------------------------------------------------------------------------


def _new_shape_tool() -> tuple[object, Any]:
    """A fresh, empty XCAF document and its shape tool.

    Returns the document alongside the tool; the caller must keep the
    document referenced for as long as it uses any label drawn from it --
    the document owns the label's underlying data. Verified by experiment,
    not merely conventional: once the document is released, a label drawn
    from it dangles and answers silently wrong (empty name, the document's
    own root entry, a null shape) rather than raising -- see ``StepLabel``
    below and ``docs/BACKLOG.md``'s corrected segfault-hazard entry.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDocStd import TDocStd_Document
    from OCP.XCAFApp import XCAFApp_Application
    from OCP.XCAFDoc import XCAFDoc_DocumentTool

    app = XCAFApp_Application.GetApplication_s()
    document = TDocStd_Document(TCollection_ExtendedString("MDTV-XCAF"))
    app.InitDocument(document)
    return document, XCAFDoc_DocumentTool.ShapeTool_s(document.Main())


def _a_box() -> Any:
    from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox

    return BRepPrimAPI_MakeBox(1.0, 2.0, 3.0).Shape()


def _unnamed_occurrence_document() -> tuple[object, object]:
    """One component whose *occurrence* label carries no name of its own
    while its *referred product* label does -- exactly what a raw board body
    copied into an assembly looks like. ``AddComponent`` always synthesises
    *some* name attribute, here its own indirection placeholder.

    Returns ``(document, component)``; the caller must keep both alive.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name
    from OCP.TopLoc import TopLoc_Location

    document, shapes = _new_shape_tool()

    product = shapes.AddShape(_a_box(), False)
    TDataStd_Name.Set_s(product, TCollection_ExtendedString("Sluch_PCB_1"))

    assembly = shapes.NewShape()
    TDataStd_Name.Set_s(assembly, TCollection_ExtendedString("enclosure"))
    component = shapes.AddComponent(assembly, product, TopLoc_Location())
    # Deliberately no TDataStd_Name.Set_s(component, ...): this is the
    # occurrence a real KiCad export leaves unnamed for a raw board body.
    shapes.UpdateAssemblies()
    return document, component


def _named_occurrence_document(name: str) -> tuple[object, object]:
    """A component whose *occurrence* label carries a genuine name, distinct
    from its referred product's own name.

    Returns ``(document, component)``; the caller must keep both alive.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name
    from OCP.TopLoc import TopLoc_Location

    document, shapes = _new_shape_tool()

    product = shapes.AddShape(_a_box(), False)
    TDataStd_Name.Set_s(product, TCollection_ExtendedString("Sluch_PCB_1"))

    assembly = shapes.NewShape()
    TDataStd_Name.Set_s(assembly, TCollection_ExtendedString("enclosure"))
    component = shapes.AddComponent(assembly, product, TopLoc_Location())
    TDataStd_Name.Set_s(component, TCollection_ExtendedString(name))
    shapes.UpdateAssemblies()
    return document, component


def _labelled(name: str) -> tuple[object, object]:
    """A free-standing product label carrying ``name``.

    Returns ``(document, label)``; the caller must keep both alive.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name

    document, shapes = _new_shape_tool()
    label = shapes.AddShape(_a_box(), False)
    TDataStd_Name.Set_s(label, TCollection_ExtendedString(name))
    return document, label


def _unattributed_label() -> tuple[object, object]:
    """A label carrying no ``TDataStd_Name`` attribute at all.

    ``AddShape`` sets one of its own accord ("SOLID"); ``ForgetAttribute``
    removes it, leaving the label exactly as a label that was never named.
    Returns ``(document, label)``; the caller must keep both alive.
    """
    from OCP.TDataStd import TDataStd_Name

    document, shapes = _new_shape_tool()
    label = shapes.AddShape(_a_box(), False)
    label.ForgetAttribute(TDataStd_Name.GetID_s())
    return document, label


def test_label_name_reports_the_occ_indirection_placeholder_as_unnamed() -> None:
    """An occurrence with no name of its own must read as unnamed, not as
    OCC's synthesised ``=>[0:1:1:N]`` indirection string."""
    document, component = _unnamed_occurrence_document()

    assert StepLabel(document, component).name == ""


def test_label_name_reports_a_genuine_occurrence_name_exactly() -> None:
    """The other direction of the same rule: a component whose occurrence
    label *was* named reports that name, not the placeholder and not the
    referred product's own name."""
    document, component = _named_occurrence_document("body")

    assert StepLabel(document, component).name == "body"


def test_label_name_reports_a_label_with_no_name_attribute_as_unnamed() -> None:
    """A label that was never named at all -- no placeholder, no attribute --
    reads the same as one carrying the synthesised indirection: both are
    "nobody named this", and the caller must not be able to tell them apart."""
    document, label = _unattributed_label()

    assert StepLabel(document, label).name == ""


def test_label_name_leaves_a_genuine_bracketed_colonned_name_untouched() -> None:
    """The placeholder pattern is matched with ``fullmatch``, so a genuine
    name that merely contains its punctuation -- embedded, as a prefix, or
    as a suffix -- must survive unchanged in every case."""
    embedded = "weird =>[0:1:1:34] name"
    prefixed = "prefix=>[0:1:1:34]"
    suffixed = "=>[0:1:1:34]suffix"

    for name in (embedded, prefixed, suffixed):
        document, label = _labelled(name)
        assert StepLabel(document, label).name == name


def test_the_reader_keeps_no_private_twin_of_the_name_rule() -> None:
    """``_label_name`` is the one implementation, reached only through
    ``StepLabel.name``; a private ``_name_of`` would let the reader and the
    writer disagree about what a name is."""
    import stompgeom.step as step_module

    assert not hasattr(step_module, "_name_of")


def test_steplabel_equality_is_by_field_not_by_kernel_identity() -> None:
    """A frozen dataclass compares its fields; ``TDF_Label.__eq__`` is
    CPython object identity (not the kernel's own ``IsEqual``), so two
    ``StepLabel``s are equal only when they wrap the *same* Python label
    object -- the property the anti-regraft tests below rely on."""
    document, label = _labelled("body")

    assert StepLabel(document, label) == StepLabel(document, label)


# ---------------------------------------------------------------------------
# StepLabel -- the label carries its document (ticket 34, ADR-0008)
#
# ``leaf_labels`` used to return bare ``TDF_Label`` handles whose validity
# depended on a document lifetime the return value gave no way to see. Every
# claim below is executed evidence, not narrated: `.scratch/architecture-
# review/design/wave4-t18-probes.py` (V1-V5) reproduces each one directly
# against the bare pre-ticket API, independently of these tests.
# ---------------------------------------------------------------------------


def _build_one_leaf_document() -> Any:
    """A single named leaf under a named assembly -- one label whose name,
    entry and shape should all survive its document's release once wrapped."""
    from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox
    from OCP.gp import gp_Pnt
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name
    from OCP.TDocStd import TDocStd_Document
    from OCP.TopLoc import TopLoc_Location
    from OCP.XCAFApp import XCAFApp_Application
    from OCP.XCAFDoc import XCAFDoc_DocumentTool

    app = XCAFApp_Application.GetApplication_s()
    document = TDocStd_Document(TCollection_ExtendedString("MDTV-XCAF"))
    app.InitDocument(document)

    shapes = XCAFDoc_DocumentTool.ShapeTool_s(document.Main())
    box = BRepPrimAPI_MakeBox(gp_Pnt(0.0, 0.0, 0.0), 1.0, 2.0, 3.0).Shape()
    leaf = shapes.AddShape(box, False)
    TDataStd_Name.Set_s(leaf, TCollection_ExtendedString("named-leaf"))

    assembly = shapes.NewShape()
    TDataStd_Name.Set_s(assembly, TCollection_ExtendedString("assembly"))
    component = shapes.AddComponent(assembly, leaf, TopLoc_Location())
    TDataStd_Name.Set_s(component, TCollection_ExtendedString("named-leaf"))
    shapes.UpdateAssemblies()
    return document


def test_a_steplabel_reads_correctly_after_the_document_that_produced_it_is_released() -> None:
    """Criterion 1. The composition the published surface invites: take a
    document's leaves, drop every other reference to the document, force
    collection, then read each fact back. Before this ticket ``leaf_labels``
    returned bare labels and every one of these read back wrong once the
    document was released (F1-01); wrapped in ``StepLabel``, which holds the
    document itself, all three answer correctly because the document is
    still referenced -- through the wrapper, not through caller discipline.
    """
    import gc

    def _leaves_from_a_document_nobody_else_holds() -> tuple[StepLabel, ...]:
        return leaf_labels(_build_one_leaf_document())

    from OCP.XCAFDoc import XCAFDoc_ShapeTool

    leaves = _leaves_from_a_document_nobody_else_holds()
    gc.collect()

    names = [leaf.name for leaf in leaves]
    entries = [leaf.entry for leaf in leaves]
    shapes_null = [XCAFDoc_ShapeTool.GetShape_s(leaf.label).IsNull() for leaf in leaves]

    assert names == ["named-leaf"], names
    assert entries and all(entry != "" for entry in entries), entries
    assert shapes_null == [False], shapes_null


def test_anchoring_on_the_shape_tool_or_the_root_label_does_not_keep_a_label_valid() -> None:
    """Criterion 2. The anchor is the ``TDocStd_Document`` object itself,
    nothing drawn from it: a value that instead held the document's own
    ``ShapeTool`` or its own root label (``document.Main()``) would look
    equally sound and still fail this test, because neither keeps the
    document alive. Reproduced for both wrong anchors; the owned value
    (holding the document itself) reads back correctly in the same process.
    """
    import gc

    from stompgeom.step import _label_name

    def _via_shape_tool() -> Any:
        from OCP.XCAFDoc import XCAFDoc_DocumentTool

        document = _build_one_leaf_document()
        tool = XCAFDoc_DocumentTool.ShapeTool_s(document.Main())
        (leaf,) = leaf_labels(document)
        return tool, leaf.label

    def _via_root_label() -> Any:
        document = _build_one_leaf_document()
        root = document.Main()
        (leaf,) = leaf_labels(document)
        return root, leaf.label

    def _via_document() -> StepLabel:
        (leaf,) = leaf_labels(_build_one_leaf_document())
        return leaf

    # Each scenario is built and collected on its own, one at a time --
    # matching `.scratch/architecture-review/design/wave4-t18-probes-
    # judge-v2.py` (P5) exactly, which this reproduces. Building all three
    # scenarios first and collecting once at the end does NOT reproduce the
    # defect reliably: memory the C++ side has already freed can still read
    # back its old, coherent bytes until something else overwrites them --
    # itself further evidence that a dangling label is a memory-safety
    # hazard, not a documented contract, which is exactly why this package
    # must never publish one bare.
    _tool, tool_label = _via_shape_tool()
    gc.collect()
    assert _label_name(tool_label) == "", (
        "the shape tool kept the label valid -- it should not have"
    )

    _root, root_label = _via_root_label()
    gc.collect()
    assert _label_name(root_label) == "", (
        "the document's own root label kept the label valid -- it should not have"
    )

    document_anchored = _via_document()
    gc.collect()
    assert document_anchored.name == "named-leaf"


def test_two_walks_of_one_live_document_disagree_by_identity_agree_by_entry() -> None:
    """Criterion 3, the anti-regraft test. ``TDF_Label.__eq__`` is CPython
    object identity and each walk obtains its own Python label object for
    the same node, so two ``StepLabel``s for one node compare unequal even
    though their entry strings agree and the kernel's own ``IsEqual``
    answers true. This is why the writer's ``replaced_labels`` parameter is,
    and must stay, a set of entry strings: narrowing it to a set of owned
    ``StepLabel``s would make membership silently false for the same node on
    the happy path. A diff narrowing that parameter is a defect, not this
    test's job to permit.
    """
    document = _build_one_leaf_document()

    (first,) = leaf_labels(document)
    (second,) = leaf_labels(document)

    assert first != second, "two separate kernel calls must not compare == by accident"
    assert first.entry == second.entry
    assert first.label.IsEqual(second.label)


def test_a_shape_measures_identically_whether_or_not_its_document_is_held() -> None:
    """Criterion 4, the negative half. ``TopoDS_Shape`` is independently
    reference-counted and owes nothing to its document -- unlike a label, it
    does not dangle by the document being released. Without this test,
    "these are two debts, not one" is an assertion rather than executed
    evidence, and a later wave could re-wrap the shape on the strength of
    the label's own, unrelated hazard.
    """
    import gc

    from OCP.XCAFDoc import XCAFDoc_ShapeTool

    def _shape_from_a_document_nobody_holds() -> Any:
        (leaf,) = leaf_labels(_build_one_leaf_document())
        return XCAFDoc_ShapeTool.GetShape_s(leaf.label)

    released = _shape_from_a_document_nobody_holds()
    gc.collect()

    held_document = _build_one_leaf_document()
    (held_leaf,) = leaf_labels(held_document)
    held = XCAFDoc_ShapeTool.GetShape_s(held_leaf.label)

    assert bounding_box_mm(released) == pytest.approx(bounding_box_mm(held), abs=1e-9)


# --------------------------------------------------------------------------
# ``StepSolid.box_mm``: the same box, measured once.
# --------------------------------------------------------------------------


def _unit_box(dx: float, dy: float, dz: float) -> Any:
    from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox

    return BRepPrimAPI_MakeBox(dx, dy, dz).Shape()


def test_a_solids_own_box_is_the_box_of_its_shape() -> None:
    """The memo answers what the function answers, or it is a second rule."""
    from stompgeom.step import StepSolid

    solid = StepSolid(name="BODY", shape=_unit_box(2.0, 3.0, 4.0))

    assert solid.box_mm == bounding_box_mm(solid.shape)


def test_a_solids_own_box_is_measured_once_however_often_it_is_read(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A box is an exact function of an immutable solid, and a run reads the
    same one from the scan, the clash stage and the assembly writer.

    The first assertion is this test's own control: a memo that never
    measured at all, or one seeded with a wrong value, fails it, so the
    second assertion is evidence rather than a rule that cannot fire.
    """
    import stompgeom.step as step

    calls: list[Any] = []
    real = step.bounding_box_mm

    def counted(shape: Any) -> Any:
        calls.append(shape)
        return real(shape)

    monkeypatch.setattr(step, "bounding_box_mm", counted)
    solid = step.StepSolid(name="BODY", shape=_unit_box(2.0, 3.0, 4.0))

    first = solid.box_mm
    assert len(calls) == 1

    assert solid.box_mm is first
    assert len(calls) == 1


def test_two_solids_over_the_same_shape_each_measure_their_own(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The memo belongs to the solid, not to a table keyed on something
    shared: two values wrapping one shape are two values."""
    import stompgeom.step as step

    calls: list[Any] = []
    real = step.bounding_box_mm

    def counted(shape: Any) -> Any:
        calls.append(shape)
        return real(shape)

    monkeypatch.setattr(step, "bounding_box_mm", counted)
    shape = _unit_box(2.0, 3.0, 4.0)

    assert step.StepSolid("A", shape).box_mm == step.StepSolid("B", shape).box_mm
    assert len(calls) == 2


def test_a_solids_box_does_not_join_its_equality() -> None:
    """Reading the box must not change what the value is: two equal solids
    stay equal, and one that has been measured still equals one that has not.
    """
    from stompgeom.step import StepSolid

    shape = _unit_box(2.0, 3.0, 4.0)
    measured = StepSolid("A", shape)
    _box = measured.box_mm

    assert measured == StepSolid("A", shape)
