"""The reader's own contract, apart from any enclosure that uses it."""

from __future__ import annotations

import string
from pathlib import Path
from typing import Any

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from stompgeom.step import (
    _EPOCH,
    bounding_box_mm,
    label_name,
    leaf_labels,
    read_step,
    source_timestamp,
)
from stompmodel.errors import DocumentError

from .xcaf import BODY_SIZE_MM, build_document

#: Printable ASCII with no control character and no backslash, so a
#: generated string can never hit the writer's own STEP special-character
#: encoding (``\N\``, ``\T\``, and a literal backslash's own doubling) or its
#: NUL truncation -- none of that is this reader's concern, which reads only
#: the quote-doubling ``FILE_NAME``'s own field carries (ISO 10303-21 §6).
_PLAUSIBLE_FIELD_TEXT = "".join(
    c for c in string.printable if c not in "\t\n\r\x0b\x0c\\"
)


def test_source_timestamp_reads_a_real_st_developer_header(tmp_path: Path) -> None:
    """A genuine ST-Developer file, annotated with a comment naming each
    field immediately before that field's own value -- the dialect the old
    comment-matching pattern was written for, and the one real committed
    fixture and every cached Hammond model actually use. The value must come
    from ``FILE_NAME``'s own field, not merely from the comment beside it."""
    target = tmp_path / "st-developer.stp"
    target.write_bytes(
        b"ISO-10303-21;\n"
        b"HEADER;\n"
        b"/* Generated by software containing ST-Developer\n"
        b" * from STEP Tools, Inc. (www.steptools.com) \n"
        b" */\n"
        b"\n"
        b"FILE_DESCRIPTION(\n"
        b"/* description */ (''),\n"
        b"/* implementation_level */ '2;1');\n"
        b"\n"
        b"FILE_NAME(\n"
        b"/* name */ \n"
        b"'1590B.iam.stp',\n"
        b"\n"
        b"/* time_stamp */ '2014-07-28T13:46:15-04:00',\n"
        b"/* author */ ('rboehler'),\n"
        b"/* organization */ (''),\n"
        b"/* preprocessor_version */ 'ST-DEVELOPER v15.2',\n"
        b"/* originating_system */ 'Autodesk Inventor 2014',\n"
        b"/* authorisation */ '');\n"
        b"\n"
        b"FILE_SCHEMA (('AUTOMOTIVE_DESIGN { 1 0 10303 214 3 1 1 }'));\n"
        b"ENDSEC;\n"
    )

    assert source_timestamp(target) == "2014-07-28T13:46:15-04:00"


def test_source_timestamp_falls_back_to_the_epoch_with_no_file_name(
    tmp_path: Path,
) -> None:
    """Never a clock reading: determinism does not depend on the file
    carrying a stamp, only on every write copying the same value."""
    target = tmp_path / "bare.stp"
    target.write_bytes(b"ISO-10303-21;\n")

    assert source_timestamp(target) == _EPOCH


def test_source_timestamp_falls_back_to_the_epoch_when_the_field_is_empty(
    tmp_path: Path,
) -> None:
    """A declared but empty ``time_stamp`` field degrades to the sentinel
    rather than putting an empty string into a report."""
    target = tmp_path / "empty-stamp.stp"
    target.write_bytes(b"FILE_NAME('a name','',('author'),('org'),'p','s','');\n")

    assert source_timestamp(target) == _EPOCH


def test_source_timestamp_reads_past_a_doubled_quote_in_the_preceding_field(
    tmp_path: Path,
) -> None:
    """A literal quote in the ``name`` field is written doubled (``''``);
    that must not be mistaken for the field's closing quote, which would
    otherwise hand the timestamp field's own value to the wrong capture."""
    target = tmp_path / "escaped-name.stp"
    target.write_bytes(
        b"FILE_NAME('it''s a name','2014-07-28T13:46:15-04:00',"
        b"('author'),('org'),'p','s','');\n"
    )

    assert source_timestamp(target) == "2014-07-28T13:46:15-04:00"


def test_source_timestamp_unescapes_a_doubled_quote_in_its_own_field(
    tmp_path: Path,
) -> None:
    """The timestamp field itself may carry an escaped quote; the reader
    must return the one real character, not the two-character encoding."""
    target = tmp_path / "escaped-stamp.stp"
    target.write_bytes(
        b"FILE_NAME('name','it''s stamped',('author'),('org'),'p','s','');\n"
    )

    assert source_timestamp(target) == "it's stamped"


def test_source_timestamp_pattern_has_no_catastrophic_backtracking(
    tmp_path: Path,
) -> None:
    """A run of quotes with no closing ``FILE_NAME`` call must not make the
    match pathological: each alternative in the string-literal branch
    consumes a distinct, unambiguous prefix, so this returns in linear time
    rather than hanging the process."""
    target = tmp_path / "pathological.stp"
    target.write_bytes(b"FILE_NAME(" + b"'" * 20000)

    assert source_timestamp(target) == _EPOCH


@settings(deadline=None, max_examples=25)
@given(
    timestamp=st.text(alphabet=_PLAUSIBLE_FIELD_TEXT, min_size=1, max_size=40),
)
def test_render_step_timestamp_survives_its_own_round_trip_for_any_value(
    timestamp: str, tmp_path_factory: pytest.TempPathFactory
) -> None:
    """Criterion 1's class property: no single hard-coded string can satisfy
    this, only a reader that recovers the field the writer actually set --
    whatever value that field held, including one containing the delimiters
    (``,`` ``(`` ``)``) and the quote character the writer itself escapes.

    ``tmp_path_factory``, not ``tmp_path``: a function-scoped fixture is not
    reset between ``@given`` examples, and this needs a fresh file each time.
    """
    from stompgeom.writer import render_step

    payload = render_step(
        build_document(),
        title="a title",
        timestamp=timestamp,
        originating_system="an originating system",
    )
    target = tmp_path_factory.mktemp("round-trip") / "written.stp"
    target.write_bytes(payload)

    assert read_step(target).timestamp == timestamp


def test_reading_a_missing_file_is_a_document_error(tmp_path: Path) -> None:
    """A stompgeom reader cannot raise a stompdrill error; refusing a foreign
    document is a failure any member can have, so the base is shared.

    The message says "model", not "case model": an enclosure is one thing a
    caller might have been reading, and this layer knows about none of them.
    """
    with pytest.raises(DocumentError, match="no model at"):
        read_step(tmp_path / "absent.stp")


def test_reading_a_non_step_file_is_a_document_error(tmp_path: Path) -> None:
    """Not readable is distinct from not present, and both are the file's
    fault rather than the data's."""
    target = tmp_path / "rubbish.stp"
    target.write_bytes(b"this is not a STEP file at all\n")

    with pytest.raises(DocumentError, match="is not a readable STEP file"):
        read_step(target)


# ---------------------------------------------------------------------------
# The reader driven against a file this package wrote, needing no download
# ---------------------------------------------------------------------------


def _written(tmp_path: Path) -> Path:
    """A real STEP assembly, built in memory and written by this package."""
    from stompgeom.writer import render_step

    target = tmp_path / "round-trip.stp"
    payload = render_step(
        build_document(),
        title="a round trip",
        timestamp="2020-01-02T03:04:05",
        originating_system="a supplied originating system 9.9",
    )
    target.write_bytes(payload)
    return target


def test_read_step_returns_every_leaf_solid_and_no_assembly(tmp_path: Path) -> None:
    """``leaf_labels`` recurses past an assembly label rather than recording
    it, so three components come back as three solids under their own names."""
    document = read_step(_written(tmp_path))

    assert len(document.solids) == 3
    assert {"body", "lid"} <= {solid.name for solid in document.solids}


def test_read_step_places_each_solid_in_assembly_coordinates(tmp_path: Path) -> None:
    """``leaf_labels``'s central claim: reading the *component* label applies the
    placement its parent gave it. The lid is modelled at the origin like the
    body and lifted 5 mm by the assembly, so a reader taking the referred
    product label instead would hand it back sitting at zero."""
    document = read_step(_written(tmp_path))
    (body,) = document.named("body")
    (lid,) = document.named("lid")

    assert bounding_box_mm(body.shape)[2] == pytest.approx(0.0, abs=1e-6)
    assert bounding_box_mm(lid.shape)[2] == pytest.approx(5.0, abs=1e-6)


def test_bounding_box_mm_measures_a_solid_in_millimetres(tmp_path: Path) -> None:
    """The extent the document was built with, which is also what proves the
    reader's unit normalisation left a millimetre model alone."""
    (body,) = read_step(_written(tmp_path)).named("body")
    x0, y0, z0, x1, y1, z1 = bounding_box_mm(body.shape)

    assert (x1 - x0, y1 - y0, z1 - z0) == pytest.approx(BODY_SIZE_MM, abs=1e-6)


def test_a_file_this_package_wrote_reads_back_its_own_timestamp(
    tmp_path: Path,
) -> None:
    """The layer closed under its own round trip (ADR-0008): this writer
    emits no ST-Developer ``/* time_stamp */`` comment, but it does set
    ``FILE_NAME``'s own field, and that is the field the reader now reads."""
    target = _written(tmp_path)

    assert b"'2020-01-02T03:04:05'" in target.read_bytes()
    assert read_step(target).timestamp == "2020-01-02T03:04:05"


# ---------------------------------------------------------------------------
# leaf_labels -- the one XCAF leaf descent, published for every caller
# ---------------------------------------------------------------------------


def test_leaf_labels_of_an_empty_document_is_empty() -> None:
    """No free shapes at all is not an error; it is an empty result."""
    document, _shapes = _new_shape_tool()

    assert leaf_labels(document) == ()


def test_leaf_labels_does_not_filter_a_null_shaped_leaf() -> None:
    """What a leaf is *for* is a call-site decision, not this function's:
    a leaf with no shape at all is returned like any other, not skipped."""
    from OCP.TopoDS import TopoDS_Shape

    document, shapes = _new_shape_tool()
    label = shapes.AddShape(_a_box(), False)
    shapes.SetShape(label, TopoDS_Shape())

    (found,) = leaf_labels(document)
    assert found.IsEqual(label)


def test_leaf_labels_returns_leaves_not_assemblies() -> None:
    """An assembly's own label never comes back, only its leaf components --
    the distinction ``read_step`` relies on to avoid double-counting a solid."""
    document, component = _named_occurrence_document("body")

    found = leaf_labels(document)

    assert len(found) == 1
    assert found[0].IsEqual(component)


# ---------------------------------------------------------------------------
# label_name -- the one rule for what XCAF recorded as a label's name
# ---------------------------------------------------------------------------


def _new_shape_tool() -> tuple[object, Any]:
    """A fresh, empty XCAF document and its shape tool.

    Returns the document alongside the tool; the caller must keep the
    document referenced for as long as it uses any label drawn from it --
    the document owns the label's underlying data. Verified by experiment,
    not merely conventional: once the document is garbage-collected, a label
    drawn from it dangles and this binding segfaults (exit 139) on next use
    rather than raising -- there is no exception a caller could catch instead.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDocStd import TDocStd_Document
    from OCP.XCAFApp import XCAFApp_Application
    from OCP.XCAFDoc import XCAFDoc_DocumentTool

    app = XCAFApp_Application.GetApplication_s()
    document = TDocStd_Document(TCollection_ExtendedString("MDTV-XCAF"))
    app.InitDocument(document)
    return document, XCAFDoc_DocumentTool.ShapeTool_s(document.Main())


def _a_box() -> Any:
    from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox

    return BRepPrimAPI_MakeBox(1.0, 2.0, 3.0).Shape()


def _unnamed_occurrence_document() -> tuple[object, object]:
    """One component whose *occurrence* label carries no name of its own
    while its *referred product* label does -- exactly what a raw board body
    copied into an assembly looks like. ``AddComponent`` always synthesises
    *some* name attribute, here its own indirection placeholder.

    Returns ``(document, component)``; the caller must keep both alive.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name
    from OCP.TopLoc import TopLoc_Location

    document, shapes = _new_shape_tool()

    product = shapes.AddShape(_a_box(), False)
    TDataStd_Name.Set_s(product, TCollection_ExtendedString("Sluch_PCB_1"))

    assembly = shapes.NewShape()
    TDataStd_Name.Set_s(assembly, TCollection_ExtendedString("enclosure"))
    component = shapes.AddComponent(assembly, product, TopLoc_Location())
    # Deliberately no TDataStd_Name.Set_s(component, ...): this is the
    # occurrence a real KiCad export leaves unnamed for a raw board body.
    shapes.UpdateAssemblies()
    return document, component


def _named_occurrence_document(name: str) -> tuple[object, object]:
    """A component whose *occurrence* label carries a genuine name, distinct
    from its referred product's own name.

    Returns ``(document, component)``; the caller must keep both alive.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name
    from OCP.TopLoc import TopLoc_Location

    document, shapes = _new_shape_tool()

    product = shapes.AddShape(_a_box(), False)
    TDataStd_Name.Set_s(product, TCollection_ExtendedString("Sluch_PCB_1"))

    assembly = shapes.NewShape()
    TDataStd_Name.Set_s(assembly, TCollection_ExtendedString("enclosure"))
    component = shapes.AddComponent(assembly, product, TopLoc_Location())
    TDataStd_Name.Set_s(component, TCollection_ExtendedString(name))
    shapes.UpdateAssemblies()
    return document, component


def _labelled(name: str) -> tuple[object, object]:
    """A free-standing product label carrying ``name``.

    Returns ``(document, label)``; the caller must keep both alive.
    """
    from OCP.TCollection import TCollection_ExtendedString
    from OCP.TDataStd import TDataStd_Name

    document, shapes = _new_shape_tool()
    label = shapes.AddShape(_a_box(), False)
    TDataStd_Name.Set_s(label, TCollection_ExtendedString(name))
    return document, label


def _unattributed_label() -> tuple[object, object]:
    """A label carrying no ``TDataStd_Name`` attribute at all.

    ``AddShape`` sets one of its own accord ("SOLID"); ``ForgetAttribute``
    removes it, leaving the label exactly as a label that was never named.
    Returns ``(document, label)``; the caller must keep both alive.
    """
    from OCP.TDataStd import TDataStd_Name

    document, shapes = _new_shape_tool()
    label = shapes.AddShape(_a_box(), False)
    label.ForgetAttribute(TDataStd_Name.GetID_s())
    return document, label


def test_label_name_reports_the_occ_indirection_placeholder_as_unnamed() -> None:
    """An occurrence with no name of its own must read as unnamed, not as
    OCC's synthesised ``=>[0:1:1:N]`` indirection string."""
    _document, component = _unnamed_occurrence_document()

    assert label_name(component) == ""


def test_label_name_reports_a_genuine_occurrence_name_exactly() -> None:
    """The other direction of the same rule: a component whose occurrence
    label *was* named reports that name, not the placeholder and not the
    referred product's own name."""
    _document, component = _named_occurrence_document("body")

    assert label_name(component) == "body"


def test_label_name_reports_a_label_with_no_name_attribute_as_unnamed() -> None:
    """A label that was never named at all -- no placeholder, no attribute --
    reads the same as one carrying the synthesised indirection: both are
    "nobody named this", and the caller must not be able to tell them apart."""
    _document, label = _unattributed_label()

    assert label_name(label) == ""


def test_label_name_leaves_a_genuine_bracketed_colonned_name_untouched() -> None:
    """The placeholder pattern is matched with ``fullmatch``, so a genuine
    name that merely contains its punctuation -- embedded, as a prefix, or
    as a suffix -- must survive unchanged in every case."""
    embedded = "weird =>[0:1:1:34] name"
    prefixed = "prefix=>[0:1:1:34]"
    suffixed = "=>[0:1:1:34]suffix"

    for name in (embedded, prefixed, suffixed):
        _document, label = _labelled(name)
        assert label_name(label) == name


def test_the_reader_keeps_no_private_twin_of_the_name_rule() -> None:
    """``label_name`` is the one implementation; a private ``_name_of`` would
    let the reader and the writer disagree about what a name is."""
    import stompgeom.step as step_module

    assert not hasattr(step_module, "_name_of")
