"""The Hammond 1590 enclosure catalogue, as the reference outline to match.

**Generated by ``tools/extract_1590.py`` from ``docs/1590.pdf``. Do not edit by
hand.** These are physical constants, and a value that drifts from the datasheet
is a panel drilled for a case that does not exist. Re-run the script when the
datasheet is revised; ``tests/test_enclosures.py`` re-extracts on every suite run
so a revision cannot land silently.

The reference outline an operator draws is measured artwork, off by a fraction of
a millimetre in both axes. Matching it against this catalogue turns "roughly
112 x 61" into a named enclosure, and the named enclosure's whole millimetres are
what the drawing and the drill file then agree on.

Dimensions are the datasheet's own **whole millimetres**, rounded by Hammond from
imperial originals. They are not converted back: reconstructing an inch-exact
value would invent precision the datasheet does not claim, and the whole
millimetre is the number the operator reads off the box.

Heights **include the lid**, which the datasheet states is 0.16" (4 mm). An
internal-depth question therefore needs 4 mm taken off first -- not that aidrill
asks one, since it does not model enclosures in 3-D.

A footprint, not a part, is what artwork can identify: parts differing only in
height share one outline. ``footprints()`` maps each L x W to every base part
that shares it, so a match names candidates and never guesses between them.
"""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping

__all__ = ["Enclosure", "HAMMOND_1590", "footprints"]


@dataclass(frozen=True, slots=True)
class Enclosure:
    """One catalogue part: a base designator and its outside dimensions."""

    part: str
    length_mm: int
    width_mm: int
    height_mm: int

    @property
    def footprint(self) -> tuple[int, int]:
        """The 2-D outline, which is all a panel drawing can distinguish."""
        return (self.length_mm, self.width_mm)


#: Every base part in the datasheet, ordered by footprint then height so that
#: parts sharing an outline sit together.
HAMMOND_1590: tuple[Enclosure, ...] = (
    Enclosure("1590LLB", 51, 51, 25),
    Enclosure("1590LB", 51, 51, 31),
    Enclosure("1590H", 53, 38, 31),
    Enclosure("1590Y", 92, 92, 42),
    Enclosure("1590A", 93, 39, 31),
    Enclosure("1590G", 100, 50, 26),
    Enclosure("1590G2", 100, 50, 31),
    Enclosure("1590S", 111, 82, 44),
    Enclosure("1590B", 112, 61, 31),
    Enclosure("1590B2", 112, 61, 38),
    Enclosure("1590BS", 112, 61, 38),
    Enclosure("1590B3", 116, 77, 38),
    Enclosure("1590T", 120, 80, 59),
    Enclosure("1590BB", 120, 94, 34),
    Enclosure("1590BB2", 120, 94, 38),
    Enclosure("1590BBS", 120, 94, 42),
    Enclosure("1590C", 120, 94, 57),
    Enclosure("1590CE", 120, 100, 65),
    Enclosure("1590Q", 120, 120, 34),
    Enclosure("1590U", 120, 120, 59),
    Enclosure("1590V", 120, 120, 94),
    Enclosure("1590N1", 121, 66, 40),
    Enclosure("1590KK", 125, 125, 57),
    Enclosure("1590K", 125, 125, 79),
    Enclosure("1590J", 145, 95, 49),
    Enclosure("1590XX", 145, 121, 40),
    Enclosure("1590X", 145, 121, 56),
    Enclosure("1590P1", 153, 83, 50),
    Enclosure("1590DD", 188, 120, 37),
    Enclosure("1590D", 188, 120, 56),
    Enclosure("1590E", 188, 120, 82),
    Enclosure("1590F", 188, 188, 67),
    Enclosure("1590R1", 192, 112, 61),
    Enclosure("1590DE", 200, 120, 64),
    Enclosure("1590EE", 200, 120, 85),
    Enclosure("1590BX2", 254, 70, 35),
    Enclosure("1590BX", 254, 70, 50),
)


def footprints() -> Mapping[tuple[int, int], tuple[str, ...]]:
    """Each L x W outline mapped to every base part that has it, sorted.

    Sorted, and read-only, because a matcher reports these candidates to the
    operator: an order that depended on catalogue order would make the drawing's
    text change when an unrelated part was added, and a caller that mutated the
    mapping would corrupt every later match in the process.
    """
    return _FOOTPRINTS


def _build_footprints() -> Mapping[tuple[int, int], tuple[str, ...]]:
    grouped: dict[tuple[int, int], list[str]] = {}
    for enclosure in HAMMOND_1590:
        grouped.setdefault(enclosure.footprint, []).append(enclosure.part)
    return MappingProxyType(
        {outline: tuple(sorted(parts)) for outline, parts in grouped.items()}
    )


_FOOTPRINTS = _build_footprints()
